/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { IDacFactory } from "../IDacFactory";

export class IDacFactory__factory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDacFactory {
    return new Contract(address, _abi, signerOrProvider) as IDacFactory;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getDacs",
    outputs: [
      {
        internalType: "contract IDac[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];
